version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pass12345678"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - mssql:/var/opt/mssql

volumes:
    mssql: