version: "3.9"
services:
    db:
        image: postgres
        volumes:
          - pssqldata:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - "5432:5432"
volumes:
    pssqldata: