FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ./TextService ./TextService
COPY ./RepositoryBase ./RepositoryBase
COPY ./EFRepositoryBase ./EFRepositoryBase
COPY ./AuthentificationBase ./AuthentificationBase
COPY ./TextClient ./TextClient
WORKDIR ./TextService/TextService
RUN dotnet restore "TextService.csproj"
RUN dotnet build "TextService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TextService.csproj" -c Release -o /app/publish

FROM lesson6_base AS final
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TextService.dll"]